export const STRIPE_STARTED = 'STRIPE_STARTED';
export const STRIPE_SUCCESS = 'STRIPE_SUCCESS';
export const STRIPE_FAILED = 'STRIPE_FAILED';

export const CURRENCIES_IN_PROGRESS = 'CURRENCIES_IN_PROGRESS';
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS';
export const CURRENCIES_FAILED = 'CURRENCIES_FAILED';