export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ORDERS_FAILED = 'RECEIVE_ORDERS_FAILED';
export const DELETE_ORDER_COMPLETE = 'DELETE_ORDER_COMPLETE';
