export const REQUEST_CART = 'REQUEST_CART';
export const REFRESH_CART = 'REFRESH_CART';
export const RECEIVE_CART = 'RECEIVE_CART';
export const REMOVING_CART_ITEM = 'REMOVING_CART_ITEM';
export const REMOVED_CART_ITEM = 'REMOVED_CART_ITEM';
export const UPDATING_CART_ITEM = 'UPDATING_CART_ITEM';
export const UPDATED_CART_ITEM = 'UPDATED_CART_ITEM';

export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_ERROR = 'SHOW_ERROR';