export const REQUEST_CART = 'REQUEST_CART';
export const REFRESH_CART = 'REFRESH_CART';
export const RECEIVE_CART = 'RECEIVE_CART';
export const REMOVING_CART_ITEM = 'REMOVING_CART_ITEM';
export const REMOVED_CART_ITEM = 'REMOVED_CART_ITEM';
export const UPDATING_CART_ITEM = 'UPDATING_CART_ITEM';
export const UPDATED_CART_ITEM = 'UPDATED_CART_ITEM';
export const UPDATED_CART_ITEMS = 'UPDATED_CART_ITEMS';
export const UPDATING_CART_FAILED = 'UPDATING_CART_FAILED';
export const CREATE_ORDER_IN_PROGRESS = 'CREATE_ORDER_IN_PROGRESS';
export const CREATE_ORDER_COMPLETE = 'CREATE_ORDER_COMPLETE';

export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_ERROR = 'SHOW_ERROR';

export const REQUEST_ORDERS = 'REQUEST_ORDERS';