export const REQUEST_CURRENT_LOCATION = 'REQUEST_CURRENT_LOCATION';
export const RECEIVE_CURRENT_LOCATION = 'RECEIVE_CURRENT_LOCATION';
export const RECEIVE_DEFAULT_LOCATION = 'RECEIVE_DEFAULT_LOCATION';
export const REQUEST_NODES = 'REQUEST_NODES';
export const REFRESH_NODES = 'REFRESH_NODES';
export const RECEIVE_NODES = 'RECEIVE_NODES';
export const SHOW_ERROR = 'SHOW_ERROR';

