export const REQUEST_CURRENT_LOCATION = 'REQUEST_CURRENT_LOCATION';
export const FETCHING_CURRENT_LOCATION = 'FETCHING_CURRENT_LOCATION';
export const RECEIVE_CURRENT_LOCATION = 'RECEIVE_CURRENT_LOCATION';
export const FETCHING_NODES = 'FETCHING_NODES';
export const RECEIVE_NODES = 'RECEIVE_NODES';
