export const REQUEST_USER_NODES = 'REQUEST_USER_NODES';
export const RECEIVE_USER_NODES = 'RECEIVE_USER_NODES';
export const RECEIVE_USER_NODES_FAILED = 'RECEIVE_USER_NODES_FAILED';
export const USER_NODE_REMOVED = 'USER_NODE_REMOVED';
