export const CREATE_ACCOUNT_IN_PROGRESS = 'CREATE_ACCOUNT_IN_PROGRESS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_FAILED = 'RESEND_EMAIL_FAILED';