export const REQUEST_ORDER = 'REQUEST_ORDER';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
export const DELETE_ORDER_IN_PROGRESS = 'DELETE_ORDER_IN_PROGRESS';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';