export const REQUEST_NODE = 'REQUEST_NODE';
export const RECEIVE_NODE = 'RECEIVE_NODE';
export const RECEIVE_NODE_FAILED = 'RECEIVE_NODE_FAILED';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REQUEST_NODE_DATES = 'REQUEST_NODE_DATES';
export const RECEIVE_NODE_DATES = 'RECEIVE_NODE_DATES';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const RESET_NODE = 'RESET_NODE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const RECEIVE_CART = 'RECEIVE_CART';
