export const REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS';
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';
export const RECEIVE_NOTIFICATIONS_FAILED = 'RECEIVE_NOTIFICATIONS_FAILED';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const RESET_NOTIFICATIONS_FAILED = 'RESET_NOTIFICATIONS_FAILED';