export const SHOW_ERROR = 'SHOW_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
export const TOGGLE_AUTH_FORM = 'TOGGLE_AUTH_FORM';
// Create account actions
export const CREATE_ACCOUNT_IN_PROGRESS = 'CREATE_ACCOUNT_IN_PROGRESS';
export const CREATE_ACCOUNT_COMPLETE = 'CREATE_ACCOUNT_COMPLETE';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';

// Login actions
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout actions
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Load user actions
export const LOAD_USER_IN_PROGRESS = 'LOAD_USER_IN_PROGRESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

// Payment actions
export const PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS';
export const PAYMENT_COMPLETE = 'PAYMENT_COMPLETE';