export const MAINTENANCE_MODE_ENABLED = 'MAINTENANCE_MODE_ENABLED';
export const MAINTENANCE_MODE_DISABLED = 'MAINTENANCE_MODE_DISABLED';

export const TOGGLE_AUTH_FORM = 'TOGGLE_AUTH_FORM';

// Create account actions
export const CREATE_ACCOUNT_IN_PROGRESS = 'CREATE_ACCOUNT_IN_PROGRESS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_FAILED = 'RESEND_EMAIL_FAILED';

// Login actions
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout actions
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Load user actions
export const LOAD_USER_IN_PROGRESS = 'LOAD_USER_IN_PROGRESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

// Currencies actions
export const DONATE_NOTHING_STARTED = 'DONATE_NOTHING_STARTED';
export const DONATE_NOTHING_SUCCESS = 'DONATE_NOTHING_SUCCESS';
export const DONATE_NOTHING_FAILED = 'DONATE_NOTHING_FAILED';

// Permissions
export const REFRESH_USER = 'REFRESH_USER';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const REGISTER_PUSH_NOTIFICATIONS_FAILED = 'REGISTER_PUSH_NOTIFICATIONS_FAILED';
export const REGISTER_PUSH_NOTIFICATIONS_SUCCESS = 'REGISTER_PUSH_NOTIFICATIONS_SUCCESS';
export const UNREGISTER_PUSH_NOTIFICATIONS_SUCCESS = 'UNREGISTER_PUSH_NOTIFICATIONS_SUCCESS';
export const LOCATION_PERMISSION_GRANTED = 'LOCATION_PERMISSION_GRANTED';
export const LOCATION_PERMISSION_DENIED = 'LOCATION_PERMISSION_DENIED';
export const RECEIVE_CURRENT_LOCATION = 'RECEIVE_CURRENT_LOCATION';
export const ENABLING_LOCATION_SERVICES_FAILED = 'ENABLING_LOCATION_SERVICES_FAILED';