export const TOGGLE_AUTH_FORM = 'TOGGLE_AUTH_FORM';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';

// Create account actions
export const CREATE_ACCOUNT_IN_PROGRESS = 'CREATE_ACCOUNT_IN_PROGRESS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_FAILED = 'RESEND_EMAIL_FAILED';

// Login actions
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout actions
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Load user actions
export const LOAD_USER_IN_PROGRESS = 'LOAD_USER_IN_PROGRESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

// Payment actions
export const PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';

// Currencies actions
export const CURRENCIES_IN_PROGRESS = 'CURRENCIES_IN_PROGRESS';
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS';
export const CURRENCIES_FAILED = 'CURRENCIES_FAILED';